import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/Header";
import { IBM_Plex_Sans } from "next/font/google";

const IBM = IBM_Plex_Sans({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${IBM.className} antialiased`}>
        <Header />
        <main className="px-12.5 py-3 ">{children}</main>
      </body>
    </html>
  );
}
